### ISSUE TITLE
[BUG] Component ID generation collision detected.

### ISSUE THREAD

**Issue by sha4be** [eclipse-esmf/esmf-sdk-js-schematics#74]
**How: List of performed steps**
Generate several tables and add the tables modules to a single module
**What: Actual result vs expected result**
The actual result - the issue "Component ID generation collision detected" occurred
The expected result - several generated tables can work with no issues at the same page

**Where: (e.g. component, version, url, your system info)**
The issue root cause is at the `*-TableChipListComponent` generation. the component has selector `selector: 'chip-list'`, so when several tables are generated - Angular does not know what exactly chi list should be added to a table component
here is more about the issue https://angular.io/errors/NG0912

**Comment by michelu89** [comment]
The name of the chip list is now linked to the name of the config to be generated.
