### ISSUE TITLE
[BUG] Table paginator works incorrectly in remote data loading mode

### ISSUE THREAD

**Issue by sha4be** [eclipse-esmf/esmf-sdk-js-schematics#77]
**How: List of performed steps**
1. Generate a table with a remote data loading option
2. Open the table and change the page size

**What: Actual result vs expected result**
Expected result - page size is changed, whereas total number of items stays with no changes
Actual result - page size is changed, and the total number of pages is equal to the page size

**Where: (e.g. component, version, url, your system info)**
The issue's root cause is in `table.component` `requestData` method. The following line `this.paginator.length = dataToShow.length` in incorrect because `dataToShow.length` - is the total rows at the loaded page, whereas `this.paginator.length` is the total items available to load.
I suggest removing the line to fix the issue. The total number of available rows is set correctly at the table component template `[length]="totalItems"`

**Input (files/screenshots)**
<img width="1054" alt="Screenshot 2024-04-18 at 15 55 28" src="https://github.com/eclipse-esmf/esmf-sdk-js-schematics/assets/131185633/df489bcb-c530-4469-8cfa-b95e5bd451d9">

**Comment by michelu89** [comment]
Removed "this.paginator.length = dataToShow.length;" in the code generation.
