### ISSUE TITLE
[BUG] Command Bar and Column Menu buttons tooltips are not visible

### ISSUE THREAD

**Issue by sha4be** [eclipse-esmf/esmf-sdk-js-schematics#78]
**How: List of performed steps**
1. Generate table
2. Open the table
**What: Actual result vs expected result**
Expected result - "Refresh Data", "Export", "Configuration" buttons show tooltips on hover
Actual result - no tooltips are shown
**Where: (e.g. component, version, url, your system info)**
`command-bar.component` and `table.component` specify tooltips for `mat-icon`, but after the migration to Material Components v17 the tooltips are not visible.
I suggest moving tooltips to button elements to fix the tooltips functionality

**Comment by michelu89** [comment]
Moved tooltips to the corresponding DOM see: https://github.com/eclipse-esmf/esmf-sdk-js-schematics/pull/79
