### ISSUE TITLE
[BUG] "tableUpdateFinishedEvent" fired before the actual remote data request is performed

### ISSUE THREAD

**Issue by sha4be** [eclipse-esmf/esmf-sdk-js-schematics#80]
**How: List of performed steps**
1. Generate Remote data management table
2. Run the table
**What: Actual result vs expected result**
Actual Results: `tableUpdateFinishedEvent` event is fired twice - before and after the real data request
Expected result: `tableUpdateFinishedEvent` event is fired only after a data request is performed
**Where: (e.g. component, version, url, your system info)**
The issue is at the `table.component`, `applyFilters` method. `this.tableUpdateFinishedEvent.emit()` is called right after `this.requestData();`, but because a request is asynchronous the `tableUpdateFinishedEvent` event is fired before the request is done.

**Additional context (e.g. references)**
<img width="631" alt="Screenshot 2024-04-24 at 16 10 53" src="https://github.com/eclipse-esmf/esmf-sdk-js-schematics/assets/131185633/5ab99f3c-dfca-404d-bbfc-4880da53ef04">

**Comment by michelu89** [comment]
There is a problem in the "requestData()" and should be changed or adapted there.
